import Footer from "@/components/Footer";
import { getCookies } from "cookies-next";
import { useRouter } from "next/navigation";
import Script from "next/script"
import { Toaster } from "react-hot-toast";

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (
    <html lang="en">
      <head>
        <link rel="shortcut icon" type="image/png" href="../assets/images/logos/favicon.png" />
        <link rel="stylesheet" href="../assets/css/styles.min.css" />
      </head>
      <body>
        <Toaster />
        {children}
        <Footer />
        <Script src="../assets/libs/jquery/dist/jquery.min.js"></Script>
        <Script src="../assets/libs/bootstrap/dist/js/bootstrap.bundle.min.js"></Script>
        <Script src="../assets/js/sidebarmenu.js"></Script>
        <Script src="../assets/js/app.min.js"></Script>
        <Script src="../assets/libs/simplebar/dist/simplebar.js"></Script>
        <Script src="../assets/js/dashboard.js"></Script>
      </body>
    </html>
  )
}
